
worker_heartbeat_timeout: 300000
logging:
    level: info
services:
  - module: ./lib/index.js
    entrypoint: apiServiceWorker
    conf:
        mwApis:
{% for key, value in parsoid_domains.iteritems() %}
        - uri: '{{ value }}'
          domain: '{{ key }}'  
{% endfor %}


